
mysql:
  username: root
  password: root
  schema: wallet
  url: localhost:3306

server:
  port: 8080
  undertow:
    threads:
      worker: 32 # Generally this should be reasonably high, at least 10 per CPU core: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
      io: 2 # One IO thread per CPU core is a reasonable default: https://undertow.io/undertow-docs/undertow-docs-2.1.0/index.html#listeners-2
spring:
  flyway:
    locations: classpath:db/migration/mysql
