spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
    admin:
      auto-create: false
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_URL:localhost:3306}/wallet?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DATABASE_MYSQL_USERNAME:root}
    password: ${DATABASE_MYSQL_PASSWORD:root}
