ALTER TABLE clients MODIFY COLUMN created_at DATETIME NULL;
ALTER TABLE clients MODIFY COLUMN updated_at DATETIME NULL;
ALTER TABLE accounts MODIFY COLUMN created_at DATETIME NULL;
ALTER TABLE accounts MODIFY COLUMN updated_at DATETIME NULL;
ALTER TABLE transactions MODIFY COLUMN created_at DATETIME NULL;
