POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "j@j.com"
}


#########

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
  "client_id" : "ed1d3cee-2b20-4465-afea-b4491beea57e",
  "balance": "10000"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
  "account_id_from": "ee183bda-f10b-4153-b71e-ac12968187c1",
  "account_id_to": "cb5c009c-df52-4a5c-9028-00e0381e4d04",
  "amount": 150
}
