POST https://localhost:8443/clients HTTP/2
Content-Type: application/json

{
  "name": "Teste Silva",
  "email": "teste@s.com"
}


#########

POST https://localhost:8443/accounts HTTP/2
Content-Type: application/json

{
  "client_id" : "b9d67ace-a5a0-4941-a0d7-c7b848d33211",
  "balance": "1000"
}

###

POST https://localhost:8443/transactions HTTP/2
Content-Type: application/json

{
  "account_id_from": "1c8c59ee-0b34-4de5-b9e5-16ad84a4c591",
  "account_id_to": "4cdfd92a-c056-4c50-8777-a7a0dbd50d86",
  "amount": 50
}
